baseURL = '/'
languageCode = 'zh-cn'
title = '世界一隅 | 认知能量工程'
theme = 'PaperMod'

[markup.goldmark.renderer]
  unsafe = true

[[menu.main]]
  name = "系统思维"
  url = "/posts/systems-thinking/"
  weight = 10
  identifier = "systems-thinking"

[[menu.main]]
  name = "学习方法"
  url = "/posts/learning/"
  weight = 20
  identifier = "learning"

[[menu.main]]
  name = "效率工具"
  url = "/posts/tooling/"
  weight = 30
  identifier = "tooling"

[params]
  env = 'production'
  title = '世界一隅'
  description = '在算法洪流中，守护清醒的微光。'
  DateFormat = '2006年1月2日'
  author = 'Tianbing Zhao'
  defaultTheme = 'auto'
